theme: minima
title: Belinda's Blog
author: Belinda Zhang
email: bzhang@ebnet.com
description: > # this means to ignore newlines until "baseurl:"
  Here is some info about me :)
  ![this](https://user-images.githubusercontent.com/66807472/84460422-bc843a00-ac1e-11ea-970a-bdca5a476c0b.png)
# social links
twitter_username: beilyndao # DO NOT include the @ character, or else the build will fail!
github_username:  bzhang1231234 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
